Milestone two
mariosknl/book_store pull request #2
Opened 2020-08-12 07:46 UTC by expjazz

2020-08-12 17:31 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-12 17:31 UTC, bellom commented on src/components/BooksForm.js
> +import React, { useState } from 'react';
Hi Guys, Good job so far.

Let's do some rearrangement.

Kindly move this file  into `src/container` dir

React bindings for Redux separate presentational components from container components. This approach can make your app easier to understand and allow you to more easily reuse components. In your components directory (presentational components) you have components that are not connected to the Redux store, and on your containers directory you have components that are connected to the Redux store. https://redux.js.org/basics/usage-with-react#presentational-and-container-components 

![image](https://user-images.githubusercontent.com/31897434/90045002-57080480-dcc6-11ea-8c39-129c865acf05.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-08-12 17:31 UTC, bellom commented on src/components/Book.js
> +  // eslint-disable-next-line react/forbid-prop-types
using PropTypes.shape here will allow you set a type check that is more accurate.

2020-08-12 17:31 UTC, bellom commented on src/components/Book.js
> +export default function Book(props) {
In here; I think you can simplify by using arrow function like this 👇 right?
`const Book = ({ book: { title, category } }) => (
`
then make use of PropTypes.shape to capture all the props.

2020-08-12 17:31 UTC, bellom commented on src/App.js
> +import Bookslist from './components/BooksList';
Let's do some rearrangement in here.

Kindly move `app.js` into `src/component` dir

![image](https://user-images.githubusercontent.com/31897434/90045002-57080480-dcc6-11ea-8c39-129c865acf05.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896827/

2020-08-12 17:31 UTC, bellom commented on src/components/BooksList.js
> +import React from 'react';
Kindly move this file  into `src/container` dir

2020-08-12 17:36 UTC, bellom commented on src/components/BooksForm.js
> +  };
I will advise you to work on the milestones one after another(or write inside another branch), `handleSubmit` and `handleChange` features should be in milestone 3.

2020-08-14 09:00 UTC, shshamim63 requested changes
## :recycle: Required Changes :recycle: 
___
Hi @expjazz and @mariosknl :wave:,
Almost completed this milestone, just found two issues and these are very easy to resolve. Let's fix them.
___
### :spades: Mandatory Changes :spades: 
___
- Your code should not contain any unnecessary files. But inside the component directory, there is an empty index file. please remove it.
- You forgot to add another method in the actions/index.js. Please check the comment below.
___
#### Please resolve the mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-08-14 09:00 UTC, shshamim63 commented on src/actions/index.js
> +export default addBook;
An action regarding to REMOVE_BOOK is missing in here. 
![image](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/ReduxActions/ReducxActions.png)
Please add it.

2020-08-14 09:25 UTC, expjazz commented
- We removed the empty files and added the method that was missing

2020-08-15 08:13 UTC, fatymahmed approved these changes
## Hi @expjazz @mariosknl   
### Good job making the requested changes 🎉🎉
## Status: Approved ✔️

2020-10-21 11:34 UTC, closed without merging