Milestone four
mariosknl/book_store pull request #4
Opened 2020-08-12 13:46 UTC by expjazz

### In this project, we decided to use Hooks to manage the components local state and to connect with the store. You will see that all the required functionalities and specifications still applies to the project. We are not using the mapStateToProps, and neither the connect(), instead we can access the state via the useSelector hook.

All the specs required were implemented, just using more modern tools.

2020-08-13 10:36 UTC, fatymahmed requested changes
## Hi @expjazz @mariosknl  
You have done a great job on this milestone 👏👏 however, there are a few things that we need to fix.
**See my comment below**
## Status: Changes Required ♻️
_Feel free to reach out to me on slack (Fatima) if you have any questions or need any help_

2020-08-13 10:39 UTC, fatymahmed commented on src/reducers/filter.js
> +  }
- It should default to `All`  see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone4/HandelChangeFilter.png) from Pathwright

2020-08-13 10:46 UTC, fatymahmed commented on src/components/CategoryFilter.js
> +      <option>Horror</option>
why do you have this here?  
The only category that shouldn't be in the categories list is `all` see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone4/AllReturnsAllCategories.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896829/)

2020-08-14 11:56 UTC, shshamim63 approved these changes
## :+1: Approved
___
Hi @expjazz and @mariosknl :wave: ,
Awesome job, you have successfully completed all the changes asked by the previous reviewer. Just got a simple suggestion to make. You can update your readme a bit more with the info related to set up the project in a dev end. 
___
#### This :+1: is from me, you can go ahead and merge it.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-10-21 11:35 UTC, closed without merging